version: '3.5'
services:
    www:
        image: nginx:latest
        volumes:
            - ./nginx:/etc/nginx
            - ./html:/usr/share/nginx/html
        restart: always
        networks:
            - web
        labels:
            - traefik.enable=true
            - traefik.frontend.rule=Host:media.jamesjohnson.io
            - traefik.protocol=http
            - traefik.docker.network=web

networks:
    web:
        external: true
